# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
#standalone_tags:
#  [
#    {id: 0, size: 0.24, name: "tag0"},
#    {id: 1, size: 0.24, name: "tag1"}
#  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
#tag_bundles:
#  [
#     {
#       name: 'husky_apriltag',
#       layout:
#         [
#           {id: 0, size: 1.0, x: 0, y: 0, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
#         ]
#     }
#  ]

tag_bundles:
  [
     {
       name: 'tag_bundles_downward1',
       layout:
         [
           {id: 0, size: 0.24, x: 0, y: 0, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 1, size: 0.24, x: 0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 2, size: 0.24, x: 0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 3, size: 0.24, x: -0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 4, size: 0.24, x: -0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
         ]
     },

     {
       name: 'tag_bundles_forward1',
       layout:
         [
           {id: 5, size: 0.24, x: 0, y: 0, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 6, size: 0.24, x: 0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 7, size: 0.24, x: 0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 8, size: 0.24, x: -0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 9, size: 0.24, x: -0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
         ]
     },

     {
       name: 'tag_bundles_downward2',
       layout:
         [
           {id: 10, size: 0.24, x: 0, y: 0, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 11, size: 0.24, x: 0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 12, size: 0.24, x: 0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 13, size: 0.24, x: -0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 14, size: 0.24, x: -0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
         ]
     },

     {
       name: 'tag_bundles_forward2',
       layout:
         [
           {id: 15, size: 0.24, x: 0, y: 0, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 16, size: 0.24, x: 0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 17, size: 0.24, x: 0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 18, size: 0.24, x: -0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 19, size: 0.24, x: -0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
         ]
     },

     {
       name: 'tag_bundles_downward3',
       layout:
         [
           {id: 20, size: 0.24, x: 0, y: 0, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 21, size: 0.24, x: 0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 22, size: 0.24, x: 0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 23, size: 0.24, x: -0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 24, size: 0.24, x: -0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
         ]
     },

     {
       name: 'tag_bundles_forward3',
       layout:
         [
           {id: 25, size: 0.24, x: 0, y: 0, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 26, size: 0.24, x: 0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 27, size: 0.24, x: 0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 28, size: 0.24, x: -0.3, y: 0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
           {id: 29, size: 0.24, x: -0.3, y: -0.3, z: 0, qw: 1.0, qx: 0.0, qy: .0, qz: 0.0},
         ]
     }
  ]
